[生鲜肉禽水产]
牛肉
牛里脊
牛里脊肉
牛腩肉
牛绞肉
牛腱子肉
牛腿肉
瘦牛肉
瘦牛肉卷
肥牛
肥牛卷
肥牛片
牛肉片
牛肉块
牛肉末
牛肉碎
牛肉丸
牛肉里脊
焯水牛肉
猪肉
猪瘦肉
里脊肉
里脊肉丝
猪里脊肉
猪肉末
猪肉糜
五花肉
猪前腿肉馅
猪前腿肉糜
猪梅花肉
火腿肠
无添加牛肉松
鸡腿
鸡腿肉
去骨鸡腿肉
去皮鸡腿
去骨鸡腿
去皮去骨鸡腿肉
去皮鸡腿肉
去骨去皮鸡腿肉
去皮无骨鸡腿肉
去骨鸡边腿
鸡边腿
鸡胸肉
鸡里脊肉
鸡肉肠
鸡胸肉丝
鸡胸肉末
鸡丝
虾仁
鲜虾仁
新鲜虾仁
大虾
虾滑
鲜虾滑
虾片
虾皮
虾头
龙利鱼肉
龙利鱼柳
巴沙鱼柳
鳕鱼柳
三文鱼柳
去刺三文鱼柳
去皮三文鱼排
鱼片
鲈鱼
鱿鱼
蟹柳
蟹柳丝

[新鲜蔬菜菌菇]
西兰花
花菜
白花椰菜
番茄
大番茄
熟番茄
去皮番茄
西红柿
西红柿碎
圣女果
小番茄
普罗旺斯番茄
黄瓜
黄瓜片
青瓜炒口蘑
丝瓜
苦瓜
西葫芦
西葫芦片
节瓜
栉瓜
南瓜
贝贝南瓜
冬瓜
茄子
土豆
土豆丝
土豆泥
红薯
地瓜
紫薯
山药
胡萝卜
胡萝卜丝
胡萝卜丁
胡萝卜末
红黄胡萝卜
白萝卜
凉拌萝卜菜
包菜
包菜丝
圆白菜
卷心菜
高丽菜
紫甘蓝
大白菜
大白菜叶
白菜
白菜叶
白菜帮
娃娃菜
小白菜碎
生菜
生菜丝
生菜叶
油菜
小油菜
青菜
上海青
小青菜
青江菜
菜心
时令菜心
空心菜
菠菜
茼蒿
冰菜
贡菜
西芹
芹菜
莴笋
春笋
韭黄
韭黄叶
韭黄梗
大蒜苗
香菜
香菜梗
洋葱
红葱头
白洋葱
洋葱丁
洋葱丝
大蒜
大葱
大葱白
青椒
青椒丝
甜椒
彩椒
红椒
红辣椒
青辣椒
青红椒
青红辣椒
绿豆芽
豆芽
豆角
四季豆
豌豆
新鲜嫩豌豆
青豆
青豆仁
毛豆
毛豆仁
新鲜毛豆仁
玉米
玉米粒
甜玉米粒
玉米粒碎
熟玉米粒
香菇
鲜香菇
干香菇
香菇片
口蘑
平菇
杏鲍菇
白玉菇
金针菇
蟹味菇
蘑菇
蘑菇片
菌菇
菌菇组合
木耳
裙带菜
虫草花
海苔
寿司海苔
时蔬
混合蔬菜
蔬菜
配菜

[豆制品与蛋奶]
鸡蛋
无菌蛋
无菌蛋黄
蛋黄
蛋清
鸡蛋白
鸡蛋清
鸡蛋黄
鸡蛋液
温泉蛋
咸蛋黄
熟鹌鹑蛋
鹌鹑蛋
牛奶
纯牛奶
无糖酸奶
儿童奶酪片
低脂芝士片
豆腐
老豆腐
北豆腐
嫩豆腐

[米面主食]
米饭
熟米饭
杂粮饭
杂粮米饭
杂豆饭
熟糙米饭
大米
生米
黑米
糙米
小米
藜麦
意大利面
意面
儿童意大利面
短管面
通心粉
乌冬面
新鲜乌龙面
荞麦面
拉面
宽面
面条
手工面条
挂面
儿童挂面
儿童细挂面
儿童细面条
儿童面条
儿童鲜面条
碱水面
全麦吐司
吐司
全麦面包
馒头
奶香馒头
燕麦
燕麦片
即食燕麦片
细玉米面
饺子皮
水饺皮
儿童饺子皮
儿童水饺
熟儿童水饺
生饺子
馄饨皮
鸡蛋饺子
包子面团
粉丝
魔芋丝
关东煮

[新鲜水果与坚果]
苹果
柠檬
柠檬片
柠檬汁
橙子
橙汁
小青桔
香蕉
菠萝
草莓
蓝莓
花生
坚果
混合坚果
奇亚籽
无糖可乐

[粮油调味]
食用油
芝麻香油
香油
白糖
蜂蜜
食用盐
酱油
白味噌
玉米淀粉
淀粉
番茄沙司
番茄酱
米醋
生抽
老抽
蚝油
料酒
陈醋
鸡精
儿童无辣苹果咖喱块
儿童无辣甜咖喱块

