[生鲜肉禽水产]
猪肉糜
猪肉末
猪里脊肉
猪前腿肉馅
猪前腿肉糜
猪梅花肉
五花肉
牛里脊肉
牛腩肉
牛绞肉
鲜虾仁
新鲜虾仁
龙利鱼肉
龙利鱼柳
去刺三文鱼柳
去皮三文鱼排
去骨鸡腿肉
去骨去皮鸡腿肉
去皮去骨鸡腿肉
去皮无骨鸡腿肉
鸡腿肉
鸡胸肉
鸡里脊肉
巴沙鱼柳
鳕鱼柳
去皮鸡腿肉

[新鲜蔬菜菌菇]
白花椰菜
大葱白
西兰花
熟番茄
大番茄
番茄
时令菜心
菜心
上海青
小青菜
小油菜
青江菜
大白菜
大白菜叶
高丽菜
圆白菜
卷心菜
胡萝卜
胡萝卜末
甜玉米粒
玉米粒碎
鲜香菇
香菇
干香菇
口蘑
红葱头
洋葱
大蒜
节瓜
栉瓜
土豆
黄瓜
菠菜
毛豆仁
新鲜毛豆仁
小白菜碎
青豆仁
红薯
地瓜
玉米粒

[豆制品与蛋奶]
北豆腐
老豆腐
嫩豆腐
豆腐
鸡蛋
牛奶
儿童奶酪片

[米面主食]
米饭
大米
通心粉
短管面
新鲜乌龙面
儿童意大利面
儿童挂面
儿童细挂面
儿童细面条
儿童面条
儿童鲜面条
儿童饺子皮
儿童水饺
熟儿童水饺
生饺子
包子面团

[粮油调味]
食用油
芝麻香油
香油
白糖
蜂蜜
食用盐
酱油
白味噌
玉米淀粉
淀粉
番茄沙司
番茄酱
米醋
儿童无辣苹果咖喱块
儿童无辣甜咖喱块
