"水" = "unlim"

[pantry]
"食用油" = "unlim"
"芝麻香油" = "unlim"
"香油" = "unlim"
"食用盐" = "unlim"
"酱油" = "unlim"
"白糖" = "unlim"
"蜂蜜" = "unlim"
"玉米淀粉" = "unlim"
"淀粉" = "unlim"
"白味噌" = "unlim"
"番茄沙司" = "unlim"
"番茄酱" = "unlim"
"米醋" = "unlim"
"生抽" = "unlim"
"料酒" = "unlim"
"黑胡椒" = "unlim"
"蚝油" = "unlim"
"陈醋" = "unlim"
"代糖" = "unlim"
"清水" = "unlim"
"鸡精" = "unlim"
"碱水面" = "unlim"
"老抽" = "unlim"
"零卡糖" = "unlim"
"开水" = "unlim"
"淀粉水" = "unlim"
"葱段" = "unlim"
