[pantry]
"五香粉" = "unlim"
"代糖" = "unlim"
"低卡韩式酱汁" = "unlim"
"低筋面粉" = "unlim"
"低脂沙拉酱" = "unlim"
"儿童无辣甜咖喱块" = "unlim"
"儿童无辣苹果咖喱块" = "unlim"
"八角" = "unlim"
"冰水" = "unlim"
"冷水" = "unlim"
"凉开水" = "unlim"
"十三香" = "unlim"
"味精" = "unlim"
"咖喱块" = "unlim"
"咖喱酱" = "unlim"
"大葱" = "unlim"
"大葱丝" = "unlim"
"大葱白" = "unlim"
"大蒜" = "unlim"
"姜" = "unlim"
"姜丝" = "unlim"
"姜片" = "unlim"
"孜然粉" = "unlim"
"小米椒" = "unlim"
"小米辣" = "unlim"
"小米辣末" = "unlim"
"小苏打" = "unlim"
"小葱" = "unlim"
"干辣椒" = "unlim"
"开水" = "unlim"
"拌料" = "unlim"
"拌饭酱" = "unlim"
"拌饭酱汁" = "unlim"
"提前调好的碗汁" = "unlim"
"提前调好的酱汁" = "unlim"
"料汁" = "unlim"
"料酒" = "unlim"
"桂皮" = "unlim"
"椒盐" = "unlim"
"椰子水" = "unlim"
"橄榄油" = "unlim"
"欧芹" = "unlim"
"欧芹大蒜盐" = "unlim"
"水" = "unlim"
"水淀粉" = "unlim"
"泡菜" = "unlim"
"泡香菇水" = "unlim"
"洋葱酱汁" = "unlim"
"海盐" = "unlim"
"海苔碎" = "unlim"
"淀粉" = "unlim"
"淀粉水" = "unlim"
"清水" = "unlim"
"清水淀粉水" = "unlim"
"温水" = "unlim"
"灵魂酱汁" = "unlim"
"烧烤料" = "unlim"
"热水" = "unlim"
"煮菜汤" = "unlim"
"熟海苔碎" = "unlim"
"熟白芝麻" = "unlim"
"猪油" = "unlim"
"玉米淀粉" = "unlim"
"甜面酱" = "unlim"
"生姜" = "unlim"
"生抽" = "unlim"
"番茄沙司" = "unlim"
"番茄酱" = "unlim"
"白味噌" = "unlim"
"白砂糖" = "unlim"
"白糖" = "unlim"
"白胡椒" = "unlim"
"白胡椒粉" = "unlim"
"白芝麻" = "unlim"
"盐" = "unlim"
"盐焗粉" = "unlim"
"碗汁" = "unlim"
"米醋" = "unlim"
"粗辣椒面" = "unlim"
"糖" = "unlim"
"紫菜碎" = "unlim"
"红花椒" = "unlim"
"红薯淀粉" = "unlim"
"细辣椒面" = "unlim"
"老抽" = "unlim"
"胡椒粉" = "unlim"
"腌料" = "unlim"
"芝麻盐" = "unlim"
"芝麻酱" = "unlim"
"芝麻香油" = "unlim"
"芥末" = "unlim"
"花椒" = "unlim"
"花椒水" = "unlim"
"花椒粉" = "unlim"
"花椒粒" = "unlim"
"花椒面" = "unlim"
"花生油" = "unlim"
"花生酱" = "unlim"
"茶叶" = "unlim"
"葱" = "unlim"
"葱丝" = "unlim"
"葱姜水" = "unlim"
"葱段" = "unlim"
"葱白" = "unlim"
"葱花" = "unlim"
"蒜" = "unlim"
"蒜末" = "unlim"
"蒜片" = "unlim"
"蒜瓣" = "unlim"
"蒸鱼豉油" = "unlim"
"蓝莓酱" = "unlim"
"蔬菜味增汤" = "unlim"
"蔬菜汤" = "unlim"
"薄荷叶" = "unlim"
"蚝油" = "unlim"
"蜂蜜" = "unlim"
"蜂蜜芥末酱" = "unlim"
"豆瓣酱" = "unlim"
"豆豉" = "unlim"
"辣椒油" = "unlim"
"辣椒粉" = "unlim"
"辣椒酱" = "unlim"
"辣椒面" = "unlim"
"酱汁" = "unlim"
"酱油" = "unlim"
"醋" = "unlim"
"陈醋" = "unlim"
"零卡糖" = "unlim"
"面粉" = "unlim"
"韩式泡菜" = "unlim"
"韩式辣酱" = "unlim"
"食用油" = "unlim"
"食用盐" = "unlim"
"食盐" = "unlim"
"香叶" = "unlim"
"香料" = "unlim"
"香油" = "unlim"
"香醋" = "unlim"
"鱿鱼酱" = "unlim"
"鸡汤" = "unlim"
"鸡油" = "unlim"
"鸡精" = "unlim"
"黄油" = "unlim"
"黄豆酱" = "unlim"
"黄酒" = "unlim"
"黑胡椒" = "unlim"
"黑胡椒碎" = "unlim"
"黑胡椒粉" = "unlim"
"黑胡椒酱" = "unlim"
"黑芝麻" = "unlim"
"黑芝麻酱" = "unlim"
